# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.2

mod_version=1.0.20
maven_group=santiivlog.dev
archives_base_name=svvideo

fabric_version=0.116.9+1.21.1
watermedia_version=3.0.0.21
watermedia_binaries_project=4997XcoK
watermedia_binaries_version_id=AvQh3tTO
