# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.2

mod_version=1.0.3
maven_group=santiivlog.dev
archives_base_name=svvideo

fabric_version=0.116.9+1.21.1
watermedia_version=3.0.0.21
watermedia_binaries_version=3.0.0-rc.4
watermedia_youtube_version=3.0.0-beta.7
